#!name=哔哩哔哩Lite去广告@ddgksf2013
#!desc=轻量版去广告 · Shadowrocket
#!category=ddgksf2013

[URL Rewrite]
^https?:\/\/app\.bilibili\.com\/x\/v2\/splash\/show - reject-200

[Script]
http-response ^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads
http-response ^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\? script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads
http-response ^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads
http-response ^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads
http-response ^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads
http-response ^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads
http-response ^https?:\/\/app\.bilibili\.com\/x\/v2\/search\/square script-path=https://cdn.jsdmirror.com/gh/5q68fs6b86-netizen/BiliBiliAdsLite@main/bilibili.ads.js, requires-body=true, timeout=60, tag=bilibili.ads

[MITM]
hostname = app.bilibili.com
